name: Create USer # このworkflowの名前

on:
  push:
    branches:
      - main #mainブランチにマージされた時に動作するようにする
    paths:
      - "users/*.yaml"

jobs: # jobsで実行する内容を書く
  create_user: # 実行する内容(job)の名前
    runs-on: ubuntu-latest # 実行するOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Identify changed YAML files in config
        id: changed-files
        uses: lots0logs/gh-action-get-changed-files@master
        with:
          format: "json"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Read YAML file
        id: read-config
        uses: actions/github-script@v5
        with:
          script: |
            const yaml = require('js-yaml');
            const fs = require('fs');
            const changedFiles = JSON.parse('${{ steps.changed-files.outputs.all }}');
            console.log(changedFiles);
            changedFiles.forEach(file => {
              if (file.startsWith('users/') && file.endsWith('.yaml')) {
                const configFile = yaml.load(fs.readFileSync(file, 'utf8'));
                fs.appendFileSync(process.env["GITHUB_ENV"], `SCHEMA_NAME=${configFile.schema_name}\n`);
                fs.appendFileSync(process.env["GITHUB_ENV"], `USER_NAME=${configFile.username}\n`);
                fs.appendFileSync(process.env["GITHUB_ENV"], `USER_PASSWORD=${configFile.password}\n`);
              }
            });
          debug: true

      - name: Use Env Variables
        run: |
          echo "Schema Name: ${{ env.SCHEMA_NAME }}"
          echo "DB User: ${{ env.USER_NAME }}"
          echo "DB Password: ${{ env.USER_PASSWORD }}"

      - name: create-user shellscript
        run: bash .github/workflows/create-user.sh
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          HOST_NAME: 13.112.0.29
          SCHEMA_NAME: ${{ env.SCHEMA_NAME }}
          USER_NAME: ${{ env.USER_NAME }}
          USER_PASSWORD: ${{ env.USER_PASSWORD }}
