name: Hello World # このworkflowの名前

on:
  push:
    branches:
      - main #mainブランチにマージされた時に動作するようにする

jobs: # jobsで実行する内容を書く
  say_hello: # 実行する内容(job)の名前
    runs-on: ubuntu-latest # 実行するOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: example shellscript
        run: bash .github/workflows/example.sh
